# Generated by Django 6.0.7 on 2026-07-31 02:18

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('union_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=320, null=True, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('avatar', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('verification_admin', 'Verification Admin'), ('finance_admin', 'Finance Admin'), ('support_admin', 'Support Admin'), ('content_admin', 'Content Admin')], default='user', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary'), ('prefer_not_to_say', 'Prefer Not To Say')], max_length=20, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('hair_type', models.CharField(blank=True, choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily'), ('kinky', 'Kinky')], max_length=20, null=True)),
                ('face_shape', models.CharField(blank=True, choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('oblong', 'Oblong')], max_length=20, null=True)),
                ('hairline_stage', models.SmallIntegerField(blank=True, null=True)),
                ('skin_tone', models.SmallIntegerField(blank=True, null=True)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('apple', 'Apple'), ('phone', 'Phone')], default='email', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
