# Generated by Django 6.0.7 on 2026-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('barber', 'Barber'), ('stylist', 'Stylist'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('verification_admin', 'Verification Admin'), ('finance_admin', 'Finance Admin'), ('support_admin', 'Support Admin'), ('content_admin', 'Content Admin')], default='user', max_length=50),
        ),
    ]
