# Generated by Django 6.0.7 on 2026-08-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hairstyles/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/'),
        ),
    ]
