# Generated by Django 6.0.7 on 2026-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_hairstyle_image_product_image_salon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='business_certificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc/documents/business_certificate/'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='kyc/documents/government_id/'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='salon_photo',
            field=models.FileField(blank=True, null=True, upload_to='kyc/documents/salon_photo/'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='kyc/documents/utility_bill/'),
        ),
    ]
